version: "3.9"

services:

  appb:
    build: .
    image: appb
    restart: on-failure 
    ports:
      - "8005-8007:8000"
    command: >
            sh -c "python manage.py runserver 0.0.0.0:8000"
    #sh -c "for i in {1..10}; do python manage.py startapp apps$i; done"
    networks:
      - appb-net
    mem_limit: 4096M
    cpus: 2
    deploy:
      replicas: 3
networks:
    appb-net:
        

