
version: '3.9'
services:
  zookeeper-1:
    image: confluentinc/cp-zookeeper:7.3.0
    hostname: zookeeper-1
    ports:
      - "2181:2181"
    healthcheck:
      test: echo srvr | nc zookeeper-1 2181 || exit 1
      interval: 10s
      timeout: 10s
      retries: 3
    environment:
    - ZOOKEEPER_SERVER_ID=1
    - ZOOKEEPER_CLIENT_PORT=2181
    - ZOOKEEPER_TICK_TIME=5000
    - ZOOKEEPER_INIT_LIMIT=10
    - ZOOKEEPER_SYNC_LIMIT=3
    - ZOOKEEPER_SERVERS=zookeeper-1:2888:3888;zookeeper-2:2888:3888
    networks:
      - kafka-net

  zookeeper-2:
    image: confluentinc/cp-zookeeper:7.3.0
    hostname: zookeeper-2
    ports:
      - "22181:22181"
    healthcheck:
      test: echo srvr | nc zookeeper-2 22181 || exit 1
      interval: 10s
      timeout: 10s
      retries: 3
    environment:
    - ZOOKEEPER_SERVER_ID=2
    - ZOOKEEPER_CLIENT_PORT=22181
    - ZOOKEEPER_TICK_TIME=5000
    - ZOOKEEPER_INIT_LIMIT=10
    - ZOOKEEPER_SYNC_LIMIT=3
    - ZOOKEEPER_SERVERS=zookeeper-1:2888:3888;zookeeper-2:2888:3888
    networks:
      - kafka-net

  kafka-1:
    image: confluentinc/cp-kafka:7.3.0
    hostname: kafka-1
    healthcheck:
      test: nc -z localhost 9091 || exit -1
      start_period: 15s
      interval: 5s
      timeout: 10s
      retries: 10      
    depends_on:
      - zookeeper-1
      - zookeeper-2
    ports:
      - 9091:9091
    environment:
      KAFKA_BROKER_ID: 101
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:2181,zookeeper-2:22181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9091
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-1:9091 #,PLAINTEXT_HOST://localhost:9091
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT #,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      BOOTSTRAP_SERVERS: kafka-1:9091,kafka-2:9092,kafka-3:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_DELETE_TOPIC_ENABLE: "true"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    networks:
      - kafka-net
      
  kafka-2:
    image: confluentinc/cp-kafka:7.3.0
    hostname: kafka-2
    healthcheck:
      test: nc -z localhost 9092 || exit -1
      start_period: 15s
      interval: 5s
      timeout: 10s
      retries: 10
    depends_on:
      zookeeper-1:
        condition: service_healthy
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 102
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:2181,zookeeper-2:22181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-2:9092 #,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT #,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      BOOTSTRAP_SERVERS: kafka-1:9091,kafka-2:9092,kafka-3:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_DELETE_TOPIC_ENABLE: "true"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      #KAFKA_JMX_HOSTNAME: "kafka-1"
      #KAFKA_JMX_PORT: 9999
      #KAFKA_JMX_OPTS: "-Djava.rmi.server.hostname=kafka-1
      #-Dcom.sun.management.jmxremote.local.only=false
      #-Dcom.sun.management.jmxremote.rmi.port=9999
      #-Dcom.sun.management.jmxremote.port=9999
      #-Dcom.sun.management.jmxremote.authenticate=false
      #-Dcom.sun.management.jmxremote.ssl=false"      
    networks:
      - kafka-net

  kafka-3:
    image: confluentinc/cp-kafka:7.3.0
    hostname: kafka-3
    healthcheck:
      test: nc -z localhost 9093 || exit -1
      start_period: 15s
      interval: 5s
      timeout: 10s
      retries: 10            
    depends_on:
      - zookeeper-2
    ports:
      - 9093:9093
    environment:
      KAFKA_BROKER_ID: 103
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:2181,zookeeper-2:22181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://:9093 #,PLAINTEXT_HOST://172.20.104.43:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT #,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      BOOTSTRAP_SERVERS: kafka-1:9091,kafka-2:9092,kafka-3:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_DELETE_TOPIC_ENABLE: "true"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    networks:
      - kafka-net

networks:
    kafka-net:
